In [1]:
import sqlite3
import pandas as pd
from pathlib import Path

# Path to your SQLite DB
db_path = Path("/Users/keerthanavenkatesan/Documents/Data Managment/CS210FinalProject/Spotify_Popularity_Prediction/data/spotify.db")

# Connect
conn = sqlite3.connect(db_path)
print("Connected to database:", db_path)

Connected to database: /Users/keerthanavenkatesan/Documents/Data Managment/CS210FinalProject/Spotify_Popularity_Prediction/data/spotify.db

In [2]:
# 1. Check what tables exist
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("Tables in database:\n", tables, "\n")

# 2. Check columns in the tracks table
cols = pd.read_sql("PRAGMA table_info(tracks);", conn)
print("Columns in 'tracks' table:")
display(cols)

# 3. Preview first 5 rows
preview = pd.read_sql("SELECT * FROM tracks LIMIT 5;", conn)
print("\nPreview of tracks table:")
display(preview)

Tables in database:
      name
0  tracks

Columns in 'tracks' table:

    cid              name     type  notnull dflt_value  pk
0     0        Unnamed: 0  INTEGER        0       None   0
1     1       artist_name     TEXT        0       None   0
2     2        track_name     TEXT        0       None   0
3     3          track_id     TEXT        0       None   0
4     4        popularity  INTEGER        0       None   0
5     5              year  INTEGER        0       None   0
6     6             genre     TEXT        0       None   0
7     7      danceability     REAL        0       None   0
8     8            energy     REAL        0       None   0
9     9               key  INTEGER        0       None   0
10   10          loudness     REAL        0       None   0
11   11              mode  INTEGER        0       None   0
12   12       speechiness     REAL        0       None   0
13   13      acousticness     REAL        0       None   0
14   14  instrumentalness     REAL        0       None   0
15   15          liveness     REAL        0       None   0
16   16           valence     REAL        0       None   0
17   17             tempo     REAL        0       None   0
18   18       duration_ms  INTEGER        0       None   0
19   19    time_signature  INTEGER        0       None   0
20   20        cluster_id  INTEGER        0       None   0

Preview of tracks table:

,Unnamed: 0,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,cluster_id
0,1054304,Cabas,Amor De Mis Amores,3FTqjWmL21xi4HTTOq94EQ,38,2006,alt-rock,0.725,0.553,6,...,0,0.0340,0.276000,0.000007,0.1850,0.729,90.009,206653,4,2
1,621408,Ketil Bjørnstad,Første sang,0Pt7ESPgrdTdaxp2f29hX2,11,2023,swedish,0.277,0.164,9,...,0,0.0373,0.878000,0.000181,0.3350,0.184,89.308,459733,4,1
2,1121669,Project 86,Evil (A Chorus Of Resistance),75Ub3ckaoTdzgH9Azeu8cY,38,2007,alt-rock,0.486,0.927,2,...,0,0.0428,0.000003,0.014500,0.0952,0.377,135.540,183373,4,4
3,439351,Ital Tek,Open Heart,5WEPna9GWi0NkqVLAkEKNN,18,2020,dubstep,0.411,0.442,1,...,0,0.0270,0.485000,0.926000,0.1910,0.172,174.019,347610,3,3
4,266036,I-Roy,Irie Right,6peHySxvmZaRF9YEwUsggq,18,2017,dancehall,0.748,0.660,10,...,0,0.2710,0.125000,0.000000,0.0783,0.400,75.583,196179,4,2

In [12]:
query1 = """
SELECT 
    cluster_id,
    COUNT(*) AS count,
    ROUND(AVG(popularity), 2) AS avg_popularity
FROM tracks
GROUP BY cluster_id
ORDER BY avg_popularity DESC;
"""

df_cluster_pop = pd.read_sql(query1, conn)
df_cluster_pop

   cluster_id  count  avg_popularity
0           2  30555           21.63
1           4  24657           19.10
2           5  18293           18.46
3           1   9822           16.81
4           3  14898           13.36
5           0   1775           11.33

In [ ]:
query_genre = """
SELECT 
    cluster_id,
    genre,
    COUNT(*) AS count
FROM tracks
GROUP BY cluster_id, genre
ORDER BY cluster_id, count DESC;
"""

df_cluster_genres = pd.read_sql(query_genre, conn)
df_cluster_genres.head(20)

    cluster_id        genre  count
0            0       comedy   1280
1            0   show-tunes     56
2            0       german     41
3            0      swedish     38
4            0      hip-hop     29
5            0    dancehall     23
6            0     hardcore     19
7            0        sleep     16
8            0        chill     15
9            0        samba     14
10           0       indian     13
11           0        party     11
12           0        opera     11
13           0       gospel     11
14           0         funk     11
15           0          dub     11
16           0     cantopop     11
17           0     trip-hop      9
18           0  rock-n-roll      9
19           0   industrial      9



This cluster 0 is dominated by comedy tracks (72% of the cluster).
These songs share characteristics such as high speechiness, atypical musical structure, and low mainstream appeal.
As a result, the cluster has the lowest average popularity among all clusters.

In [7]:
df_cluster_genres[df_cluster_genres["cluster_id"] == 1].head(60)

     cluster_id              genre  count
69            1            ambient   1354
70            1              sleep   1298
71            1            new-age   1237
72            1          classical   1182
73            1             guitar    821
74            1              piano    701
75            1              opera    542
76            1             german    353
77            1               jazz    308
78            1             french    205
79            1           acoustic    188
80            1              chill    155
81            1             indian    147
82            1              tango    135
83            1               folk    118
84            1         show-tunes    111
85            1        black-metal    101
86            1            romance     75
87            1               club     67
88            1         psych-rock     60
89            1            swedish     57
90            1         industrial     46
91            1            spanish     45
92            1  singer-songwriter     44
93            1              samba     41
94            1           trip-hop     36
95            1               goth     31
96            1         electronic     29
97            1            electro     28
98            1          indie-pop     23
99            1             garage     21
100           1                dub     21
101           1        rock-n-roll     20
102           1     minimal-techno     19
103           1             groove     18
104           1                emo     17
105           1              blues     16
106           1               funk     15
107           1              party     12
108           1               soul     11
109           1                sad     11
110           1              k-pop     11
111           1             gospel      9
112           1           alt-rock      9
113           1             techno      8
114           1          grindcore      6
115           1           pop-film      5
116           1             comedy      5
117           1           cantopop      5
118           1             trance      4
119           1                pop      4
120           1     detroit-techno      4
121           1           afrobeat      4
122           1         songwriter      3
123           1              metal      3
124           1        heavy-metal      3
125           1              dance      3
126           1            country      3
127           1               rock      2
128           1          hard-rock      2

Cluster 1 represents low-energy, highly acoustic music such as ambient, sleep tracks, classical compositions, piano solos, and new-age genres.
These tracks share properties like soft dynamics, slow tempo, high acousticness, and low danceability.

In [8]:
df_cluster_genres[df_cluster_genres["cluster_id"] == 2].head(60)

     cluster_id              genre  count
137           2          dancehall   1487
138           2              forro   1386
139           2              salsa   1319
140           2              dance   1064
141           2              k-pop   1050
142           2            hip-hop   1040
143           2              disco    904
144           2           pop-film    877
145           2              samba    837
146           2            spanish    781
147           2          sertanejo    778
148           2               funk    747
149           2            country    738
150           2             french    636
151           2                ska    631
152           2              blues    619
153           2           afrobeat    618
154           2             gospel    616
155           2              party    596
156           2           alt-rock    596
157           2        rock-n-roll    593
158           2                dub    583
159           2          power-pop    501
160           2         deep-house    487
161           2             german    428
162           2                emo    427
163           2             garage    424
164           2             indian    418
165           2            electro    398
166           2            swedish    386
167           2           hardcore    385
168           2               soul    381
169           2              chill    381
170           2             groove    364
171           2                sad    352
172           2           acoustic    352
173           2               folk    332
174           2                edm    332
175           2           cantopop    315
176           2          indie-pop    307
177           2  singer-songwriter    295
178           2               club    287
179           2          breakbeat    271
180           2         psych-rock    269
181           2               jazz    251
182           2           trip-hop    247
183           2                pop    247
184           2               goth    235
185           2         industrial    233
186           2          punk-rock    211
187           2          hard-rock    210
188           2         electronic    198
189           2             comedy    182
190           2              house    180
191           2               punk    171
192           2      chicago-house    154
193           2               rock    132
194           2        heavy-metal    130
195           2  progressive-house    121
196           2         show-tunes    101

Cluster 2 contains high-energy, dance-oriented tracks spanning genres such as dancehall, salsa, K-pop, hip-hop, disco, EDM, and funk.
These genres share strong beats, high danceability, energetic profiles, and global popularity.

In [16]:
for cid in [3, 4, 5]:
    print(f"Cluster {cid}")
    display(df_cluster_genres[df_cluster_genres["cluster_id"] == cid].head(30))

Cluster 3

     cluster_id              genre  count
218           3     minimal-techno   1209
219           3         deep-house    851
220           3      drum-and-bass    665
221           3          breakbeat    558
222           3  progressive-house    526
223           3        black-metal    524
224           3              chill    520
225           3             techno    504
226           3                dub    486
227           3             trance    466
228           3           trip-hop    457
229           3               club    412
230           3             indian    377
231           3         industrial    356
232           3         electronic    354
233           3                edm    335
234           3             groove    305
235           3               jazz    301
236           3        death-metal    284
237           3              disco    282
238           3            electro    277
239           3     detroit-techno    277
240           3           afrobeat    277
241           3      chicago-house    272
242           3            ambient    269
243           3          hardstyle    255
244           3            dubstep    244
245           3               goth    226
246           3               funk    207
247           3             garage    204

Cluster 4

     cluster_id          genre  count
300           4    death-metal   1244
301           4    black-metal   1125
302           4      grindcore   1119
303           4            emo   1093
304           4    heavy-metal   1028
305           4       hardcore    872
306           4      hard-rock    852
307           4       alt-rock    845
308           4           goth    838
309           4      hardstyle    757
310           4      power-pop    734
311           4         garage    659
312           4     industrial    550
313           4          blues    525
314           4            ska    514
315           4            dub    478
316           4        spanish    476
317           4         gospel    472
318           4      metalcore    463
319           4          metal    456
320           4  drum-and-bass    451
321           4         groove    408
322           4         german    350
323           4      sertanejo    337
324           4        country    328
325           4      punk-rock    320
326           4     psych-rock    313
327           4          dance    306
328           4           punk    303
329           4          k-pop    278

Cluster 5

     cluster_id              genre  count
382           5              tango   1096
383           5           acoustic    961
384           5             gospel    827
385           5           cantopop    817
386           5               folk    776
387           5  singer-songwriter    715
388           5             indian    644
389           5         show-tunes    617
390           5        rock-n-roll    600
391           5              opera    599
392           5              samba    497
393           5            country    483
394           5               jazz    479
395           5           pop-film    448
396           5              blues    439
397           5            romance    419
398           5              k-pop    396
399           5              chill    385
400           5             guitar    382
401           5             french    376
402           5          sertanejo    374
403           5         psych-rock    324
404           5          indie-pop    299
405           5            spanish    296
406           5           alt-rock    239
407           5               soul    238
408           5              piano    217
409           5                emo    210
410           5          power-pop    195
411           5            new-age    194

 cluster 3 is defined by high-intensity electronic genres (minimal-techno, deep-house, DnB, trance, EDM), mixed with experimental or darker tones (black-metal, industrial, trip-hop, goth).
 cluster 4 is overwhelmingly rock, metal, hardcore, punk, goth, and other loud or alternative subgenres.
 cluster 5 represents instrumentals, classic styles, and world genres.

In [14]:
query_top_artists = """
SELECT 
    cluster_id,
    artist_name,
    COUNT(*) AS track_count
FROM tracks
GROUP BY cluster_id, artist_name
HAVING track_count >= 5
ORDER BY cluster_id, track_count DESC;
"""

df_top_artists = pd.read_sql(query_top_artists, conn)
df_top_artists.head(20)

    cluster_id          artist_name  track_count
0            0      Henning Mankell           36
1            0         Jim Gaffigan           22
2            0         Eddie Izzard           19
3            0        Alonzo Bodden           18
4            0           Jim Norton           17
5            0        Die 3 vom Ast           15
6            0           Todd Barry           13
7            0     Steve Hofstetter           13
8            0       Jim Florentine           12
9            0           Dave Waite           12
10           0  Comedian Bob Marley           12
11           0    Christopher Titus           12
12           0           Bill Hicks           12
13           0     Keith Alberstadt           11
14           0     Jeanne Robertson           11
15           0          Shane Mauss           10
16           0           Myq Kaplan           10
17           0          Mitch Fatel           10
18           0        Matt Braunger           10
19           0         Margaret Cho           10

In [17]:
for cid in [0,1,2,3, 4, 5]:
    print(f" Cluster {cid} ---")
    display(df_top_artists[df_top_artists["cluster_id"] == cid].head(30))

 Cluster 0 ---

    cluster_id          artist_name  track_count
0            0      Henning Mankell           36
1            0         Jim Gaffigan           22
2            0         Eddie Izzard           19
3            0        Alonzo Bodden           18
4            0           Jim Norton           17
5            0        Die 3 vom Ast           15
6            0           Todd Barry           13
7            0     Steve Hofstetter           13
8            0       Jim Florentine           12
9            0           Dave Waite           12
10           0  Comedian Bob Marley           12
11           0    Christopher Titus           12
12           0           Bill Hicks           12
13           0     Keith Alberstadt           11
14           0     Jeanne Robertson           11
15           0          Shane Mauss           10
16           0           Myq Kaplan           10
17           0          Mitch Fatel           10
18           0        Matt Braunger           10
19           0         Margaret Cho           10
20           0          Roy Wood Jr            9
21           0       Neil Hamburger            9
22           0           Louis C.K.            9
23           0     Kathleen Madigan            9
24           0       Dry Bar Comedy            9
25           0        Doug Stanhope            9
26           0        Bill Santiago            9
27           0            Redd Foxx            8
28           0      Lavell Crawford            8
29           0    Lachlan Patterson            8

 Cluster 1 ---

     cluster_id                       artist_name  track_count
86            1                       Traditional          261
87            1             Johann Sebastian Bach          169
88            1           Wolfgang Amadeus Mozart           83
89            1              Ludwig van Beethoven           67
90            1                   Little Symphony           66
91            1                      Jim Brickman           63
92            1                     Andrei Krylov           63
93            1                       Hans Zimmer           61
94            1                    Steven Halpern           60
95            1                 Giacomo Meyerbeer           55
96            1                       Max Richter           51
97            1                       Piano Peace           49
98            1                   Frédéric Chopin           48
99            1                   Astor Piazzolla           47
100           1                    Giuseppe Verdi           45
101           1                     Nature Sounds           40
102           1                 Alexandre Desplat           40
103           1                   Giacomo Puccini           39
104           1                       Leo Brouwer           38
105           1  Twinkle Twinkle Little Rock Star           36
106           1        Robbins Island Music Group           34
107           1                     Massage Tribe           34
108           1                 Felix Mendelssohn           34
109           1               Dmitri Shostakovich           34
110           1                    Andrés Segovia           34
111           1                      Philip Glass           33
112           1                      Greg Maroney           33
113           1            George Frideric Handel           33
114           1                       Peter Kater           31
115           1                  Fariborz Lachini           31

 Cluster 2 ---

     cluster_id         artist_name  track_count
505           2       Jack Hartmann           63
506           2         Vybz Kartel           61
507           2          Sonu Nigam           44
508           2              Pritam           44
509           2        Udit Narayan           43
510           2  Madhu Balakrishnan           41
511           2       Lasse Stefanz           37
512           2       Grateful Dead           37
513           2          Unni Menon           29
514           2        Elephant Man           29
515           2             Karthik           28
516           2         Buju Banton           28
517           2             Luciano           27
518           2      Forró do Muido           27
519           2        Denise Gagne           27
520           2  Yuvan Shankar Raja           26
521           2           Glee Cast           26
522           2          Beenie Man           26
523           2             Popcaan           25
524           2        Oscar D'León           25
525           2                 Nas           24
526           2        Dennis Brown           24
527           2     Brasas do Forró           24
528           2   Teodoro & Sampaio           23
529           2     Michael Wendler           23
530           2              Mavado           23
531           2            Capleton           23
532           2      Wisin & Yandel           22
533           2     Raí Saia Rodada           22
534           2            Deekline           22

 Cluster 3 ---

      cluster_id       artist_name  track_count
1910           3     Grateful Dead           32
1911           3  Armin van Buuren           32
1912           3     Orlando Voorn           30
1913           3     Boris Brejcha           27
1914           3        Lemongrass           26
1915           3        Louie Vega           25
1916           3            Tiësto           24
1917           3        Huda Hudia           23
1918           3           DJ 3000           23
1919           3           Surgeon           22
1920           3          OnDaMiKe           22
1921           3          Niereich           22
1922           3              Slam           21
1923           3         DJ Pierre           21
1924           3          Röyksopp           20
1925           3     Robbie Rivera           20
1926           3   Kadri Gopalnath           20
1927           3          deadmau5           19
1928           3              UMEK           19
1929           3        Frankyeffe           19
1930           3      Ellen Allien           19
1931           3    Above & Beyond           18
1932           3           Calibre           17
1933           3              Seba           16
1934           3      Paul van Dyk           16
1935           3    Massive Attack           16
1936           3            Jovonn           16
1937           3    Jesse Saunders           16
1938           3           Colombo           16
1939           3       Celldweller           16

 Cluster 4 ---

      cluster_id            artist_name  track_count
2535           4       Armin van Buuren           35
2536           4            SICK LEGEND           30
2537           4                   Rush           26
2538           4  Agoraphobic Nosebleed           26
2539           4                Sabaton           25
2540           4       Guided By Voices           24
2541           4           Napalm Death           23
2542           4             Ningen Isu           22
2543           4                  Nasum           22
2544           4            Iron Maiden           22
2545           4          Alkaline Trio           22
2546           4      Within Temptation           21
2547           4                Kamelot           21
2548           4                Lollies           20
2549           4              Green Day           20
2550           4          Grateful Dead           20
2551           4               Amorphis           20
2552           4                 U.D.O.           19
2553           4          Pig Destroyer           19
2554           4              Sepultura           18
2555           4                   Korn           18
2556           4                  KMFDM           18
2557           4           Demon Hunter           18
2558           4                   Zany           17
2559           4            The Pitcher           17
2560           4            Rabbit Junk           17
2561           4                 Phobia           17
2562           4               Mastodon           17
2563           4              Katatonia           17
2564           4          Elvis Presley           17

 Cluster 5 ---

      cluster_id            artist_name  track_count
3675           5          Grateful Dead          116
3676           5            Traditional           72
3677           5          Elvis Presley           64
3678           5       Francisco Canaro           61
3679           5    Andrew Lloyd Webber           47
3680           5        Carlos Di Sarli           39
3681           5          Willie Nelson           34
3682           5           Denise Gagne           33
3683           5          Aníbal Troilo           33
3684           5     Alfredo De Angelis           33
3685           5      Giacomo Meyerbeer           32
3686           5               Alan Tam           31
3687           5         Maria Bethânia           29
3688           5  Johann Sebastian Bach           29
3689           5          Hank Williams           29
3690           5         Giuseppe Verdi           29
3691           5       Osvaldo Pugliese           27
3692           5           Tita Merello           26
3693           5          Roberto Firpo           26
3694           5         Nana Mouskouri           26
3695           5       Stephen Sondheim           25
3696           5         Edmundo Rivero           24
3697           5        Astor Piazzolla           24
3698           5       Sudha Ragunathan           23
3699           5      Libertad Lamarque           23
3700           5           Boyce Avenue           23
3701           5       Alberto Castillo           23
3702           5        Nikolay Kopylov           22
3703           5        Lata Mangeshkar           22
3704           5         Juan D'Arienzo           22

In [18]:
query_stats = """
SELECT 
    cluster_id,
    ROUND(AVG(danceability), 3) AS avg_danceability,
    ROUND(AVG(energy), 3) AS avg_energy,
    ROUND(AVG(loudness), 3) AS avg_loudness,
    ROUND(AVG(speechiness), 3) AS avg_speechiness,
    ROUND(AVG(acousticness), 3) AS avg_acousticness,
    ROUND(AVG(instrumentalness), 3) AS avg_instrumentalness,
    ROUND(AVG(liveness), 3) AS avg_liveness,
    ROUND(AVG(valence), 3) AS avg_valence,
    ROUND(AVG(tempo), 3) AS avg_tempo
FROM tracks
GROUP BY cluster_id
ORDER BY cluster_id;
"""

df_cluster_stats = pd.read_sql(query_stats, conn)
df_cluster_stats

,cluster_id,avg_danceability,avg_energy,avg_loudness,avg_speechiness,avg_acousticness,avg_instrumentalness,avg_liveness,avg_valence,avg_tempo
0,0,0.574,0.611,-12.802,0.836,0.728,0.022,0.641,0.474,100.780
1,1,0.334,0.166,-21.380,0.050,0.880,0.763,0.153,0.187,103.455
2,2,0.680,0.734,-6.543,0.095,0.213,0.037,0.187,0.703,118.579
3,3,0.614,0.732,-8.774,0.066,0.101,0.774,0.165,0.385,127.105
4,4,0.412,0.851,-5.506,0.098,0.064,0.134,0.320,0.345,135.666
5,5,0.518,0.380,-10.766,0.056,0.689,0.085,0.197,0.399,113.639

In [19]:
query_similar_tracks = """
WITH target AS (
    SELECT 
        danceability AS t_dance,
        energy AS t_energy,
        loudness AS t_loud,
        valence AS t_valence,
        tempo AS t_tempo,
        genre AS t_genre,
        cluster_id AS t_cluster
    FROM tracks
    WHERE track_id = '3FTqjWmL21xi4HTTOq94EQ'
)

SELECT
    tr.track_name,
    tr.artist_name,
    tr.genre,
    tr.popularity,

    -- Manhattan distance combining 5 key audio features
    ABS(tr.danceability - target.t_dance) +
    ABS(tr.energy - target.t_energy) +
    ABS(tr.loudness - target.t_loud) +
    ABS(tr.valence - target.t_valence) +
    ABS(tr.tempo - target.t_tempo) AS similarity_score

FROM tracks tr, target
WHERE tr.track_id != '3FTqjWmL21xi4HTTOq94EQ'
  AND tr.cluster_id = target.t_cluster      -- filter to same cluster
  AND tr.genre = target.t_genre             -- optional tighter filter

ORDER BY similarity_score ASC
LIMIT 10; """

df_similar_tracks = pd.read_sql(query_similar_tracks, conn)
df_similar_tracks

,track_name,artist_name,genre,popularity,similarity_score
0,Let It Go,Tenth Avenue North,alt-rock,27,0.585
1,Oye cantinero,El Tri,alt-rock,44,0.713
2,El Castigo,Los Master Plus,alt-rock,55,1.190
3,Breakdown,Icon For Hire,alt-rock,40,1.381
4,So What,The Mowgli's,alt-rock,38,1.389
5,Listen Out Loud,DREAMERS,alt-rock,35,1.583
6,"Revenge, And a Little More",Unlike Pluto,alt-rock,47,1.711
7,No Other Place,Hollywood Undead,alt-rock,42,1.865
8,World In My Pocket,The Unlikely Candidates,alt-rock,46,2.128
9,Worried Moon,Chris Cornell,alt-rock,39,2.236